### ISSUE TITLE
Codes for MAY221

### ISSUE THREAD

**Issue by amanmodiii** [swoyam2609/CodeChef-Solution#16]
Hey @swoyam2609 ,
I would like to upload solutions for the problems of May Long One 22.
Would you mark it under hacktoberfest ?
Regards.

**Comment by swoyam2609** [comment]
Cool, assigning it to you, create a proper directory and upload your codes
Happy Contributing

**Comment by swoyam2609** [comment]
Closed as completed by @amanmodiii
