### ISSUE TITLE
Codes of STARTER 39

### ISSUE THREAD

**Issue by amanmodiii** [swoyam2609/CodeChef-Solution#18]

**Comment by amanmodiii** [comment]
Thanks.

**Comment by jayprakash6547** [comment]
Hi please assign this issue to me

**Comment by swoyam2609** [comment]
Okay Assigned to @jayprakash6547 
Happy Contributing

**Comment by swoyam2609** [comment]
NOTE: As you have requested to solve two issues, I suggest you to resolve both and then open a single pull request. Multiple pull requests won't be accepted as it then counts to spamming the contest
