### ISSUE TITLE
Opening up of New Issues

### ISSUE THREAD

**Issue by swoyam2609** [swoyam2609/CodeChef-Solution#26]
## Requirements
 - We want someone to go through all the directories that are currently existing in the repository and add README.md files if not present
 - The Contributors can also add new issues and their respective directories in the repository inviting other contributors to contribute in the repository

**Contributors who wish to solve only one of the above issues can also take it up**

**Comment by abhinaba-dash** [comment]
I can add README.md files to each directories. Please assign this issue to me @swoyam2609

**Comment by swoyam2609** [comment]
Primary issue solved by @abhinaba-dash

**Comment by swoyam2609** [comment]
### Contributors who can add new issues and their respective directories in the repository inviting other contributors to contribute to the repository
