### ISSUE TITLE
Codes of September Long

### ISSUE THREAD

**Issue by swoyam2609** [swoyam2609/CodeChef-Solution#7]

**Comment by KuSantosh100** [comment]
Can anyone assign me this issue ?
I can add the solutions (probably 6 qs out of 8 ) that I have solved here.

**Comment by swoyam2609** [comment]
Okay assigned,
Happy contributing

**Comment by swoyam2609** [comment]
Compleed by @KuSantosh100

**Comment by KuSantosh100** [comment]
Thank you @swoyam2609
